### PR TITLE
Error status should deserialise as a string.

### PR DESCRIPTION
**Pull request by derekdowling**
See http://jsonapi.org/format/#error-objects.

### CODE REVIEW

**Comment by derekdowling** [comment]
Good catch! Proactively ensuring this makes it back into master. Should add a test to ensure that this part of the specification is always met in the future as well.

**Comment by jkongie** [comment]
Thanks! I wasn't sure exactly where to write the test but I'm happy to add one if with a bit of guideance.

**Comment by derekdowling** [comment]
Actually, I am fine without tests on this. Probably going to be more work than it is worth manually regexing.

**Comment by jkongie** [comment]
Cheers!

**Pull request merged**
